dist: trusty
jobs:
  include:
    - stage: build docker image
      script:
      - echo ${TRAVIS_COMMIT}
      - echo ${TRAVIS_BRANCH}
      - docker login --username AWS -p ${AWS_PASS} 332220437127.dkr.ecr.eu-central-1.amazonaws.com/interviewtest
      - docker build -t ${TRAVIS_BRANCH}-${TRAVIS_COMMIT} .
      - docker tag ${TRAVIS_BRANCH}-${TRAVIS_COMMIT} 332220437127.dkr.ecr.eu-central-1.amazonaws.com/interviewtest:${TRAVIS_BRANCH}-${TRAVIS_COMMIT}
      - docker push 332220437127.dkr.ecr.eu-central-1.amazonaws.com/interviewtest:${TRAVIS_BRANCH}-${TRAVIS_COMMIT}
      - docker images
    - stage: start docker
    - script: docker images
    - script: 
      - |
      docker login --username AWS -p ${AWS_PASS} 332220437127.dkr.ecr.eu-central-1.amazonaws.com/interviewtest
      docker run -d -p 8081:8081 332220437127.dkr.ecr.eu-central-1.amazonaws.com/interviewtest:${TRAVIS_BRANCH}-${TRAVIS_COMMIT}
    - stage: test
    - script: 
      - |
        if [ $(curl -LI http://localhost:8081/about -o /dev/null -w '%{http_code}\n' -s) == "200" ]
        then 
          exit 0
        else
          exit 1
        fi 
      - |
        answer="$(curl  http://localhost:8081 -s)"
        if [[ $answer == "Hello Damir" ]]
        then 
          exit 0
        else
          exit 1
        fi
      - |
        answer="$(curl  http://localhost:8081/about -s)"
        STR="+31 20 12345678"
        if [[ "$answer" =~ .*"$STR" ]]
        then 
          exit 0
        else
          exit 1
        fi 
    - stage: deploy
      deploy:
      - provider: elasticbeanstalk
        access_key_id: "${AWS_ACCESS_KEY}"
        secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
        region: "eu-central-1"
        app: "Damir"
        env: "Damir-env"
        bucket_name: "24i-build-artifact"
        bucket_path: "Damir"

  # deploy:

    # - provider: s3
    #   access_key_id: "${AWS_ACCESS_KEY}"
    #   secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
    #   bucket: "24i-build-artifact"

    #comment