dist: trusty
jobs:
  include:
    - stage: build docker image
      script:
      - echo ${TRAVIS_COMMIT}
      - echo ${TRAVIS_BRANCH}
      #- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t ${TRAVIS_BRANCH}-${TRAVIS_COMMIT} .
      - docker images
    - stage: test
      script: docker run -p 8081:8081 $TRAVIS_COMMIT
      script: 
      - |
        if [ $(curl -LI http://localhost:8081/about -o /dev/null -w '%{http_code}\n' -s) == "200" ]
        then 
          exit 0
        else
          exit 1
        fi 
      # script: ./second_test.sh
      # # script: ./third_test.sh

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "${AWS_ACCESS_KEY}"
  secret_access_key:
    secure: "${AWS_SECRET_ACCESS_KEY}"
  region: "eu-central-1"
  app: "Damir"
  env: "Damir-env"
  bucket_name: "24i-build-artifact"